### ISSUE TITLE
Need to connect with you

### ISSUE THREAD

**Issue by adilSofyrus** [Mozammalhossainsobug/chat-bot-flutter#1]
How to connect with you linkedIn twitter any info 
update your git profile and added your how to connect 
need your help regarding this repo.

**Comment by Mozammalhossainsobug** [comment]
hello, sorry for the late reply. How can i help you?

**Comment by adilSofyrus** [comment]
> hello, sorry for the late reply. How can i help you?

Thanks for response i just want to know how you have build the application can you provide a detail read me file so that it becomes easy to use your git repo 
i fond this repo very helpful in building the chat bot

**Comment by Mozammalhossainsobug** [comment]
Thank you for your feedback. I'm currently busy now so hopefully readme file will be updated very soon.

**Comment by adilSofyrus** [comment]
thanks

**Comment by Mozammalhossainsobug** [comment]
Would you like to check the readme file now? I'll be waiting for your feedback.
